name: Update IPTV

on:
  schedule:
    - cron: '0 23 * * *' # 每天 UTC 时间 23 点（北京时间次日凌晨 7 点）执行
  workflow_dispatch: # 允许你在网页上点按钮手动运行，方便调试

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'


       # ---- 新增这一步：安装简繁转换核心库 ----
      - name: Install dependencies
        run: npm install opencc-js

      - name: Run script hn
        run: node index-hn.js
        
      - name: Run script cn
        run: node index-cn.js

      # 新增：运行我们刚写的 EPG 合并脚本
      - name: Run EPG merge script
        run: node epg-merge.js

      - name: 提交并推送到仓库
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 重点修改：把 M3U 列表和刚刚生成的 epg.xml 一起添加到提交队列
          git add kankan-hn.m3u kankan-cn.m3u epg.xml
          
          # 如果文件没有变化，commit 会报错退出，所以加了 || true 忽略报错
          git commit -m "Auto update IPTV and EPG" || true
          git push
